# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Joshua Goth's Journey into the Web-Dev
email: me@JoshuaGoth.com
description: >- # this means to ignore newlines until "baseurl:"
 Joshua Goth's Journey into Web Development. I am a retired network engineer and beginning my journey into Web Development.
  I am not motivated by financial or monitary gain, but to learn what I have 
  been wanting to learn for years. As a writer and inventor, I am driven to create. I am walking this path on my own, and I am looking forward to sharing
  what I have learned along my journey to become a Web Developer.
baseurl: "github" # the subpath of your site, e.g. /blog
url: "http://JoshuaGoth.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NA
github_username:  JoshuaGoth

# Build settings
#theme: minima
remote_theme: broccolini/swiss
#theme: no-style-please
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
